# -*- coding: utf-8 -*-
"""7.4_T5

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pvUtQ9L2IDAFs6JAyVZHEuEM4H5OG9WZ
"""

!pip install datasets===2.14.6

import numpy as np
from datasets import load_dataset, Dataset
from transformers import (
    T5Tokenizer,
    T5ForConditionalGeneration,
    TrainingArguments,
    Trainer,
    DataCollatorForSeq2Seq,
)

# Amazon removed the "amazon_us_reviews" dataset, so we'll have to use a replacement here.
dataset_category = "Software" # "Electronics" you can also choose electronics like in the lesson, but the dataset is bigger and loading will take longer

meta_ds = load_dataset("McAuley-Lab/Amazon-Reviews-2023", f"raw_meta_{dataset_category}", split='full').to_pandas()[['parent_asin', 'title']]
review_ds = load_dataset("McAuley-Lab/Amazon-Reviews-2023", f"raw_review_{dataset_category}", split='full').to_pandas()[['parent_asin', 'rating', 'text', 'verified_purchase']]

ds = meta_ds.merge(review_ds, on='parent_asin', how='inner').drop(columns="parent_asin")
ds = ds.rename(columns={"rating":"star_rating", "title":"product_title", "text":"review_body"})

ds = ds[ds['verified_purchase'] & (ds['review_body'].map(len) > 100)].sample(100_000)
ds

dataset = Dataset.from_pandas(ds)

#Encoding 'star_rading' column, so the model should not suffer from bias, as can see large amount of 5 star rating (as described in course)
dataset = dataset.class_encode_column("star_rating")

"""The stratify_by_column="star_rating" argument in dataset.train_test_split() ensures that the train and test splits maintain the same proportion of samples for each unique value in the star_rating column."""

# Splitting the dataset into training and testing sets
dataset = dataset.train_test_split(test_size=0.1, seed=42)#, stratify_by_column="star_rating")

train_dataset = dataset['train']
test_dataset = dataset['test']
print(train_dataset[0])

MODEL_NAME = 't5-base'
tokenizer = T5Tokenizer.from_pretrained('t5-base')

# Defining the function to preprocess the data
def preprocess_data(examples):
    examples['prompt'] = [f"review: {product_title}, {star_rating} Stars!" for product_title, star_rating in zip(examples['product_title'], examples['star_rating'])]
    examples['response'] = [f"{review_body}" for review_body in examples['review_body']]

    inputs = tokenizer(examples['prompt'], padding='max_length', truncation=True, max_length=128)
    targets = tokenizer(examples['response'], padding='max_length', truncation=True, max_length=128)

    # Set -100 at the padding positions of target tokens
    target_input_ids = []
    for ids in targets['input_ids']:
        target_input_ids.append([id if id != tokenizer.pad_token_id else -100 for id in ids])

    inputs.update({'labels': target_input_ids})
    return inputs

from transformers import DataCollatorWithPadding

train_dataset = train_dataset.map(preprocess_data, batched=True)
test_dataset = test_dataset.map(preprocess_data, batched=True)

data_collator = DataCollatorWithPadding(tokenizer=tokenizer)

model = T5ForConditionalGeneration.from_pretrained(MODEL_NAME)

TRAINING_OUTPUT = "./models/t5_fine_tuned_reviews"
training_args = TrainingArguments(
    output_dir=TRAINING_OUTPUT,
    num_train_epochs=3,
    per_device_train_batch_size=12,
    per_device_eval_batch_size=12,
    save_strategy='epoch',
)

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset,
    data_collator=data_collator,
)

trainer.train()

trainer.save_model(TRAINING_OUTPUT)

model = T5ForConditionalGeneration.from_pretrained(TRAINING_OUTPUT)

# Defining the function to generate reviews
def generate_review(text):
    inputs = tokenizer("review: " + text, return_tensors='pt', max_length=512, padding='max_length', truncation=True)
    outputs = model.generate(inputs['input_ids'], max_length=128, no_repeat_ngram_size=3, num_beams=6, early_stopping=True)
    summary = tokenizer.decode(outputs[0], skip_special_tokens=True)
    return summary

# Generating reviews for random products
random_products = test_dataset.shuffle(42).select(range(100))['product_title']

print(generate_review(random_products[0] + ", 3 Stars!"))

print(generate_review(random_products[8] + ", 5 Stars!"))

print(generate_review(random_products[50] + ", 2 Stars!"))

print(generate_review(random_products[9] + ", 2 Stars!"))

print(generate_review(random_products[99] + ", 2 Stars!"))